package jaime.canvas;

import javax.swing.DefaultListModel;


/**
 *
 * @author jaime
 */
public class CanvasModel extends javax.swing.JFrame {

    DefaultListModel listModel = new DefaultListModel();
    AddData dialog = new AddData();
    
    public void addListElements(String element) {
        listModel.addElement(element);
    }
    
    public void openDialog(AddData dialog) {
        dialog.setVisible(true);
    }
    
    public String getDialogDescription(AddData dialog) {
        return dialog.getDescription();
        
    }
    
    public String getDialogHeader(AddData dialog) {
        return dialog.getHeader();
    }
    
    /**
     * Creates new form canvasModel
     */
    public CanvasModel() {
        initComponents();
        jListPartners.setModel(listModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        panelClients = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnClients = new javax.swing.JButton();
        deleteClient = new javax.swing.JButton();
        addClient = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListClients = new javax.swing.JList<>();
        panelStreams = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnStreams = new javax.swing.JButton();
        addStream = new javax.swing.JButton();
        deleteStream = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListStreams = new javax.swing.JList<>();
        panelResources = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnResources = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListResources = new javax.swing.JList<>();
        deleteResources = new javax.swing.JButton();
        addResources = new javax.swing.JButton();
        panelActivities = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnActivities = new javax.swing.JButton();
        deleteActivity = new javax.swing.JButton();
        addActivity = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jListActivities = new javax.swing.JList<>();
        panelRelations = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnRelations = new javax.swing.JButton();
        deleteRelation = new javax.swing.JButton();
        addRelation = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListRelation = new javax.swing.JList<>();
        panelChannels = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnChannels = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListChannels = new javax.swing.JList<>();
        deleteChannel = new javax.swing.JButton();
        addChannel = new javax.swing.JButton();
        panelProposal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnProposal = new javax.swing.JButton();
        deleteProposal = new javax.swing.JButton();
        addProposal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPurpose = new javax.swing.JList<>();
        panelPartners = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnPartners = new javax.swing.JButton();
        addPartner = new javax.swing.JButton();
        deletePartner = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPartners = new javax.swing.JList<>();
        panelCosts = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCosts = new javax.swing.JButton();
        deleteCost = new javax.swing.JButton();
        addCost = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jListCosts = new javax.swing.JList<>();

        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi CANVAS");
        setMinimumSize(new java.awt.Dimension(1002, 512));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        panelClients.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Segmentos de clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelClients.setMinimumSize(new java.awt.Dimension(180, 20));
        panelClients.setPreferredSize(new java.awt.Dimension(180, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/clientes.png"))); // NOI18N

        btnClients.setText("Detalles");

        deleteClient.setText("-");

        addClient.setText("+");

        jListClients.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListClients);

        javax.swing.GroupLayout panelClientsLayout = new javax.swing.GroupLayout(panelClients);
        panelClients.setLayout(panelClientsLayout);
        panelClientsLayout.setHorizontalGroup(
            panelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientsLayout.createSequentialGroup()
                        .addGroup(panelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelClientsLayout.createSequentialGroup()
                                .addComponent(addClient, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnClients))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(panelClientsLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        panelClientsLayout.setVerticalGroup(
            panelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientsLayout.createSequentialGroup()
                .addGroup(panelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelClientsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addClient)
                            .addComponent(deleteClient))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClients)
                .addContainerGap())
        );

        panelStreams.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flujos de ingresos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelStreams.setMinimumSize(new java.awt.Dimension(473, 116));
        panelStreams.setPreferredSize(new java.awt.Dimension(473, 116));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/fuentes_ingresos.png"))); // NOI18N

        btnStreams.setText("Detalles");

        addStream.setText("+");
        addStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStreamActionPerformed(evt);
            }
        });

        deleteStream.setText("-");

        jListStreams.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jListStreams);

        javax.swing.GroupLayout panelStreamsLayout = new javax.swing.GroupLayout(panelStreams);
        panelStreams.setLayout(panelStreamsLayout);
        panelStreamsLayout.setHorizontalGroup(
            panelStreamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStreamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStreams)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelStreamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addStream, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStream, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelStreamsLayout.setVerticalGroup(
            panelStreamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStreamsLayout.createSequentialGroup()
                .addGroup(panelStreamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelStreamsLayout.createSequentialGroup()
                        .addComponent(addStream)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteStream)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStreamsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStreams)
                .addContainerGap())
            .addGroup(panelStreamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelResources.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recursos clave", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelResources.setMinimumSize(new java.awt.Dimension(180, 180));
        panelResources.setPreferredSize(new java.awt.Dimension(180, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/recursos_clave.png"))); // NOI18N

        btnResources.setText("Detalles");

        jListResources.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jListResources);

        deleteResources.setText("-");

        addResources.setText("+");

        javax.swing.GroupLayout panelResourcesLayout = new javax.swing.GroupLayout(panelResources);
        panelResources.setLayout(panelResourcesLayout);
        panelResourcesLayout.setHorizontalGroup(
            panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResourcesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addComponent(btnResources)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(addResources, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteResources, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addComponent(jScrollPane8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))))
        );
        panelResourcesLayout.setVerticalGroup(
            panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResourcesLayout.createSequentialGroup()
                .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelResourcesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panelResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResources)
                    .addComponent(addResources)
                    .addComponent(deleteResources))
                .addContainerGap())
        );

        panelActivities.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actividades clave", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelActivities.setMinimumSize(new java.awt.Dimension(180, 180));
        panelActivities.setPreferredSize(new java.awt.Dimension(180, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/actividades_clave.png"))); // NOI18N

        btnActivities.setText("Detalles");

        deleteActivity.setText("-");

        addActivity.setText("+");

        jListActivities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jListActivities);

        javax.swing.GroupLayout panelActivitiesLayout = new javax.swing.GroupLayout(panelActivities);
        panelActivities.setLayout(panelActivitiesLayout);
        panelActivitiesLayout.setHorizontalGroup(
            panelActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActivitiesLayout.createSequentialGroup()
                        .addComponent(addActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(panelActivitiesLayout.createSequentialGroup()
                        .addComponent(btnActivities)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane10))
                .addContainerGap())
        );
        panelActivitiesLayout.setVerticalGroup(
            panelActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActivitiesLayout.createSequentialGroup()
                .addGroup(panelActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelActivitiesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addActivity)
                            .addComponent(deleteActivity))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActivities)
                .addContainerGap())
        );

        panelRelations.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relación con el cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelRelations.setMinimumSize(new java.awt.Dimension(180, 180));
        panelRelations.setPreferredSize(new java.awt.Dimension(180, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/rel_cliente.png"))); // NOI18N

        btnRelations.setText("Detalles");

        deleteRelation.setText("-");

        addRelation.setText("+");

        jListRelation.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jListRelation);

        javax.swing.GroupLayout panelRelationsLayout = new javax.swing.GroupLayout(panelRelations);
        panelRelations.setLayout(panelRelationsLayout);
        panelRelationsLayout.setHorizontalGroup(
            panelRelationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRelationsLayout.createSequentialGroup()
                        .addComponent(btnRelations)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRelationsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(addRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelRelationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRelationsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addGap(5, 5, 5)))
        );
        panelRelationsLayout.setVerticalGroup(
            panelRelationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelationsLayout.createSequentialGroup()
                .addGroup(panelRelationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRelationsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRelationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addRelation)
                            .addComponent(deleteRelation))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRelations)
                .addContainerGap())
            .addGroup(panelRelationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelationsLayout.createSequentialGroup()
                    .addContainerGap(74, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)))
        );

        panelChannels.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Canales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelChannels.setMinimumSize(new java.awt.Dimension(180, 180));
        panelChannels.setPreferredSize(new java.awt.Dimension(180, 180));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/canal_distrib.png"))); // NOI18N

        btnChannels.setText("Detalles");
        btnChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChannelsActionPerformed(evt);
            }
        });

        jListChannels.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListChannels);

        deleteChannel.setText("-");

        addChannel.setText("+");

        javax.swing.GroupLayout panelChannelsLayout = new javax.swing.GroupLayout(panelChannels);
        panelChannels.setLayout(panelChannelsLayout);
        panelChannelsLayout.setHorizontalGroup(
            panelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChannelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelChannelsLayout.createSequentialGroup()
                        .addGroup(panelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChannels)
                            .addGroup(panelChannelsLayout.createSequentialGroup()
                                .addComponent(addChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelChannelsLayout.setVerticalGroup(
            panelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChannelsLayout.createSequentialGroup()
                .addGroup(panelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelChannelsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelChannelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addChannel)
                            .addComponent(deleteChannel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChannels)
                .addContainerGap())
        );

        panelProposal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propuestas de valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelProposal.setMinimumSize(new java.awt.Dimension(180, 20));
        panelProposal.setPreferredSize(new java.awt.Dimension(180, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/propuesta_valor.png"))); // NOI18N

        btnProposal.setText("Detalles");

        deleteProposal.setText("-");
        deleteProposal.setMaximumSize(new java.awt.Dimension(22, 31));
        deleteProposal.setMinimumSize(new java.awt.Dimension(22, 31));
        deleteProposal.setPreferredSize(new java.awt.Dimension(22, 31));

        addProposal.setText("+");

        jListPurpose.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListPurpose);

        javax.swing.GroupLayout panelProposalLayout = new javax.swing.GroupLayout(panelProposal);
        panelProposal.setLayout(panelProposalLayout);
        panelProposalLayout.setHorizontalGroup(
            panelProposalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProposalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProposalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProposalLayout.createSequentialGroup()
                        .addComponent(addProposal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteProposal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProposalLayout.createSequentialGroup()
                        .addComponent(btnProposal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelProposalLayout.setVerticalGroup(
            panelProposalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProposalLayout.createSequentialGroup()
                .addGroup(panelProposalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProposalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelProposalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addProposal)
                            .addComponent(deleteProposal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProposal)
                .addContainerGap())
        );

        panelPartners.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Key Partners", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelPartners.setMinimumSize(new java.awt.Dimension(190, 20));
        panelPartners.setName("keyParterns"); // NOI18N
        panelPartners.setPreferredSize(new java.awt.Dimension(190, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/socios_clave.png"))); // NOI18N

        btnPartners.setText("Detalles");

        addPartner.setText("+");
        addPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPartnerActionPerformed(evt);
            }
        });

        deletePartner.setText("-");

        jListPartners.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListPartners);

        javax.swing.GroupLayout panelPartnersLayout = new javax.swing.GroupLayout(panelPartners);
        panelPartners.setLayout(panelPartnersLayout);
        panelPartnersLayout.setHorizontalGroup(
            panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPartnersLayout.createSequentialGroup()
                .addGroup(panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPartnersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPartners)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPartnersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPartnersLayout.createSequentialGroup()
                                .addComponent(addPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletePartner, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelPartnersLayout.setVerticalGroup(
            panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPartnersLayout.createSequentialGroup()
                .addGroup(panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPartnersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPartnersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPartner)
                            .addComponent(deletePartner))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPartners)
                .addContainerGap())
        );

        panelCosts.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estructura de costos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        panelCosts.setMinimumSize(new java.awt.Dimension(473, 116));
        panelCosts.setPreferredSize(new java.awt.Dimension(473, 116));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaime/canvas/images/estructura_costos.png"))); // NOI18N

        btnCosts.setText("Detalles");

        deleteCost.setText("-");

        addCost.setText("+");
        addCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCostActionPerformed(evt);
            }
        });

        jListCosts.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jListCosts);

        javax.swing.GroupLayout panelCostsLayout = new javax.swing.GroupLayout(panelCosts);
        panelCosts.setLayout(panelCostsLayout);
        panelCostsLayout.setHorizontalGroup(
            panelCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCostsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCosts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCost, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCost, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
            .addGroup(panelCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCostsLayout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );
        panelCostsLayout.setVerticalGroup(
            panelCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCostsLayout.createSequentialGroup()
                .addGroup(panelCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCostsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCosts))
                    .addComponent(jLabel8)
                    .addGroup(panelCostsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteCost)))
                .addContainerGap())
            .addGroup(panelCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCostsLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPartners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelActivities, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(panelResources, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelProposal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelChannels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRelations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelClients, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCosts, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelStreams, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRelations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelChannels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelProposal, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(panelPartners, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelActivities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelResources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelClients, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelStreams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChannelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChannelsActionPerformed

    private void addCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCostActionPerformed

    private void addStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStreamActionPerformed

    private void addPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPartnerActionPerformed
        // TODO add your handling code here:
        openDialog(dialog);
    }//GEN-LAST:event_addPartnerActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        if(dialog.getListFlag())
            addListElements(getDialogHeader(dialog));
        dialog.setListFlag(false);
    }//GEN-LAST:event_formWindowGainedFocus

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CanvasModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CanvasModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CanvasModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CanvasModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //Jbutton button = new JButton();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new CanvasModel().setVisible(true);
            }
        });
        
      /*  addPartner.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });*/
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addActivity;
    private javax.swing.JButton addChannel;
    private javax.swing.JButton addClient;
    private javax.swing.JButton addCost;
    private javax.swing.JButton addPartner;
    private javax.swing.JButton addProposal;
    private javax.swing.JButton addRelation;
    private javax.swing.JButton addResources;
    private javax.swing.JButton addStream;
    private javax.swing.JButton btnActivities;
    private javax.swing.JButton btnChannels;
    private javax.swing.JButton btnClients;
    private javax.swing.JButton btnCosts;
    private javax.swing.JButton btnPartners;
    private javax.swing.JButton btnProposal;
    private javax.swing.JButton btnRelations;
    private javax.swing.JButton btnResources;
    private javax.swing.JButton btnStreams;
    private javax.swing.JButton deleteActivity;
    private javax.swing.JButton deleteChannel;
    private javax.swing.JButton deleteClient;
    private javax.swing.JButton deleteCost;
    private javax.swing.JButton deletePartner;
    private javax.swing.JButton deleteProposal;
    private javax.swing.JButton deleteRelation;
    private javax.swing.JButton deleteResources;
    private javax.swing.JButton deleteStream;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jListActivities;
    private javax.swing.JList<String> jListChannels;
    private javax.swing.JList<String> jListClients;
    private javax.swing.JList<String> jListCosts;
    private javax.swing.JList<String> jListPartners;
    private javax.swing.JList<String> jListPurpose;
    private javax.swing.JList<String> jListRelation;
    private javax.swing.JList<String> jListResources;
    private javax.swing.JList<String> jListStreams;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel panelActivities;
    private javax.swing.JPanel panelChannels;
    private javax.swing.JPanel panelClients;
    private javax.swing.JPanel panelCosts;
    private javax.swing.JPanel panelPartners;
    private javax.swing.JPanel panelProposal;
    private javax.swing.JPanel panelRelations;
    private javax.swing.JPanel panelResources;
    private javax.swing.JPanel panelStreams;
    // End of variables declaration//GEN-END:variables
}
